# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hthomas <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/21 19:28:51 by hthomas           #+#    #+#              #
#    Updated: 2018/07/21 19:28:53 by hthomas          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

PROG = colle-2
CFLAGS = -Wall -Werror -Wextra
SRCS = *.c

all:  
	gcc $(SRCS) -o $(PROG) #$(CFLAGS)

fclean:
	/bin/rm -f $(PROG)

re: fclean all
